sonar.projectKey=mytimeclick_geospatial_7ca627e5-825a-49bc-a9cb-101db3236c7c
sonar.python.version=3.10
#sonar.host.url=http://localhost:9000
sonar.host.url=http://sonarcube.unternhub.at:9000
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S1192
sonar.issue.ignore.multicriteria.e1.resourceKey=**
sonar.issue.ignore.multicriteria.e2.ruleKey=xml:S125
sonar.issue.ignore.multicriteria.e3.ruleKey=python:S125
sonar.issue.ignore.multicriteria.e4.ruleKey=python:S1192
sonar.issue.ignore.multicriteria.e4.resourceKey=**
sonar.issue.ignore.multicriteria.e5.ruleKey=python:S2245
sonar.issue.ignore.multicriteria.e5.resourceKey=*base_geoengine/fields.py
sonar.issue.ignore.multicriteria.e6.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.e6.resourceKey=**/base_geoengine/fields.py
sonar.issue.ignore.multicriteria.e7.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.e7.resourceKey=**/base_geoengine/models/base.py
sonar.exclusions=tests/**,migrations/**,scripts/experimental/**,**/description/index.html,*.cjs,**/base_geoengine/static/src/**,**/lib/**,**/base_geoengine_demo/**
